name: Chai's Choice Pet Products
favicon: null
layout_spectrum: 0.4041758084204048
typography_spectrum: 0.28442829730920494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#500b08'
    - '#6fa700'
    - '#ffffff'
    - '#9e400d'
    - '#ffff00'
  brandStrength: 0.3125
  lightness: 0.8766262209974229
  saturation: 0.487341444240883
  rhythmicContrast: 0.8949214303866029
purpose: []
